kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mysqlstorageclassrbdpvc
spec:
  accessModes:
      - ReadWriteOnce #只能指定ReadWriteOnce或者ReadOnlyMany
  resources:
      requests:
        storage: 1Gi
  storageClassName: defaultstorageclass #此处需要指定storageClassName为上一步的storageclass的name
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  ports:
  - port: 3306
  selector:
    app: mysql
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  serviceName: "mysql"
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: 172.16.202.3/cloudmanager/mariadb:10.3.12
        name: mysql
        env:
          # Use secret in real usage
        - name: MYSQL_ROOT_PASSWORD
          value: password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysqlstorageclassrbdpvc
          mountPath: /var/lib/mysql
      imagePullSecrets:
      - name: gypregsecret
      volumes:
      - name: mysqlstorageclassrbdpvc
        persistentVolumeClaim:
          claimName: mysqlstorageclassrbdpvc  #此处指定pvc
