apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  serviceName: "mysql"
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: 172.30.120.161/cloudmanager/mariadb:10.3.12
        name: mysql
        env:
          # Use secret in real usage
        - name: MYSQL_ROOT_PASSWORD
          value: password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysqlstorageclassrbdpvc
          mountPath: /var/lib/mysql
      imagePullSecrets:
      - name: gypregsecret
      volumes:
      - name: mysqlstorageclassrbdpvc
        persistentVolumeClaim:
          claimName: mysqlstorageclassrbdpvc  #此处指定pvc
