apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"name":"nginx"},"name":"nginxnew","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"name":"nginxnew"}},"template":{"metadata":{"labels":{"name":"nginxnew"}},"spec":{"containers":[{"args":["nginx","-g","daemon off;"],"image":"172.30.120.161/google_containers/nginx:new","imagePullPolicy":"IfNotPresent","name":"nginx","ports":[{"containerPort":80,"protocol":"TCP"}]}]}}}}
  creationTimestamp: "2020-03-24T04:09:15Z"
  generation: 1
  labels:
    name: nginx
  name: nginxnew
  namespace: default
  resourceVersion: "13059538"
  selfLink: /apis/apps/v1/namespaces/default/deployments/nginxnew
  uid: 39a4f058-6d85-11ea-9ae0-fa163eaa773f
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: nginxnew
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: nginxnew
    spec:
      containers:
      - args:
        - nginx
        - -g
        - daemon off;
        image: 172.30.120.161/google_containers/nginx:new
        imagePullPolicy: IfNotPresent
        name: nginx
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2020-03-24T04:09:19Z"
    lastUpdateTime: "2020-03-24T04:09:19Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2020-03-24T04:09:15Z"
    lastUpdateTime: "2020-03-24T04:09:19Z"
    message: ReplicaSet "nginxnew-766bb45c5b" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
