apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx123
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx123
  template:
    metadata:
      labels:
        app: nginx123
    spec:
      containers:
        - name: nginx123
          image: 172.30.120.161/google_containers/nginx:new
          ports:
            - containerPort: 80
          imagePullPolicy: Always